MobileTracker/Models/Db/Device.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace MobileTracker.Models.Db
{
    public class Device
    {
        public int DeviceId { get; set; }
        [Required]
        [Display(Name = "Zařízení")]
        public string Name { get; set; }

        [Required]
        [Remote("IsImeiAvailable", "Device", AdditionalFields="DeviceId", ErrorMessage = "Zařízení s tímto Imei již v systému existuje.")]
        public string Imei { get; set; }

        [Display(Name = "Telefonní číslo")]
        public string PhoneNumber { get; set; }

        [Required]
        [Display(Name = "Id skupiny")]
        public int GroupId { get; set; }

        [Display(Name = "Skupina")]
        public virtual Group Group { get; set; }

        public virtual ICollection<Event> Events { get; set; }
        public virtual ICollection<Gps> Gpses { get; set; }
        public virtual ICollection<Message> Messages { get; set; } 
    }
}

MobileTracker/Controllers/DeviceController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MobileTracker.Models;
using MobileTracker.Models.Db;

namespace MobileTracker.Controllers
{
    public class DeviceController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Device/
        public ActionResult Index()
        {
            var devices = db.Devices.Include(d => d.Group);
            return View(devices.ToList());
        }

        // GET: /Device/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            GpsMapTimeSelect mapTimeSelect = new GpsMapTimeSelect();
            mapTimeSelect.Device = device;
            mapTimeSelect.DeviceId = device.DeviceId;
            return View(mapTimeSelect);
        }

        // GET: /Device/Create
        public ActionResult Create()
        {
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name");
            return View();
        }

        // POST: /Device/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="DeviceId,Name,Imei,PhoneNumber,GroupId")] Device device)
        {
            if (ModelState.IsValid)
            {
                db.Devices.Add(device);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name", device.GroupId);
            return View(device);
        }

        // GET: /Device/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name", device.GroupId);
            return View(device);
        }

        // POST: /Device/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="DeviceId,Name,Imei,PhoneNumber,GroupId")] Device device)
        {
            if (ModelState.IsValid)
            {
                db.Entry(device).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name", device.GroupId);
            return View(device);
        }

        // GET: /Device/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // POST: /Device/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Device device = db.Devices.Find(id);
            db.Devices.Remove(device);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        public ActionResult IndexUserView()
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            var group = user.Group;
            var devices = group.Devices;
            return View(devices.ToList());
        }

        public JsonResult IsImeiAvailable(string imei, int deviceId)
        {
            return Json(!db.Devices.Any(i => i.Imei == imei && i.DeviceId != deviceId), JsonRequestBehavior.AllowGet);
        }
    }
}

MobileTracker/Controllers/GpsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MobileTracker.Models;
using MobileTracker.Models.Manager;

namespace MobileTracker.Controllers
{
    public class GpsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [Authorize(Roles = IdentityManager.RoleUser)]
        public ActionResult MapActualPosition(int deviceId)
        {
//            var timestamp = DateManager.ToUnixTimestamp(DateTime.UtcNow) - 5 * DateManager.DAY_SECOND;
            var gpsQuery = from g in db.Gpses select g;
            gpsQuery = gpsQuery.Where(g => g.DeviceId.Equals(deviceId));
            gpsQuery = gpsQuery.OrderByDescending(g => g.Time);
            return View(gpsQuery.First());
        }

        [Authorize(Roles = IdentityManager.RoleUser)]
        public ActionResult MapDateInterval(int deviceId, int timeFrom, int timeTo)
        {
            var gpsQuery = from g in db.Gpses select g;
            gpsQuery = gpsQuery.Where(g => g.DeviceId.Equals(deviceId) && g.Time > timeFrom && g.Time < timeTo);
            gpsQuery = gpsQuery.OrderBy(g => g.Time);
            ViewData["test"] = gpsQuery.ToList().Count;
            return View(gpsQuery.ToList());
        }
    }
}

MobileTracker/Views/Device/Create.cshtml
@model MobileTracker.Models.Db.Device

@{
    ViewBag.Title = "Vytvořit";
}

<h2>Create</h2>


@using (Html.BeginForm("createDevice")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Device</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imei, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imei)
                @Html.ValidationMessageFor(model => model.Imei)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber)
                @Html.ValidationMessageFor(model => model.PhoneNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupId, "GroupId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GroupId", String.Empty)
                @Html.ValidationMessageFor(model => model.GroupId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Vytvořit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zpět na seznam", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MobileTracker/Views/Device/Delete.cshtml
@model MobileTracker.Models.Db.Device

@{
    ViewBag.Title = "Smazat";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Device</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Group.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Group.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Imei)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Imei)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Zpět na seznam", "Index")
        </div>
    }
</div>

MobileTracker/Views/Device/Details.cshtml
@using MobileTracker.Models
@model GpsMapTimeSelect

@{
    ViewBag.Title = "Detail";
}

<h2>Zařízení</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Device.Group.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Device.Group.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Device.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Device.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Device.Imei)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Device.Imei)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Device.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Device.PhoneNumber)
        </dd>

    </dl>
</div>
<hr />
@using (Html.BeginForm("MapDateInterval", "Gps", FormMethod.Post, new { id = "mapDateInterval" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.DeviceId)
    @Html.TextBoxFor(model => model.TimeFrom, new { @style = "visibility: hidden; height: 0; float: left; width: 0;" })
    @Html.TextBoxFor(model => model.TimeTo, new { @style = "visibility: hidden; height: 0; float: left; width: 0;" })
    <h4>Zobrazit na mapě období</h4>
    <div class="form-horizontal">
        <hr />

        <div class="form-group">
            <div class='col-md-8'>
                <div class="col-md-2">
                    @Html.LabelFor(model => model.TimeFrom)
                </div>
                <div class='col-md-4 input-group date' id='datetimepickerFrom'>
                    <input type='text' name="timeFromString" class="form-control" onclick="$('#datetimepickerFrom').data('DateTimePicker').show()" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                <div class="col-md-4">@Html.ValidationMessageFor(model => model.TimeFrom)</div>
            </div>
        </div>
        <div class="form-group">
            <div class='col-md-8'>
                <div class='col-md-2'>
                    @Html.LabelFor(model => model.TimeTo)
                </div>
                <div class='col-md-4 input-group date' id='datetimepickerTo'>
                    <input type='text' name="timeToString" class="form-control" onclick="$('#datetimepickerTo').data('DateTimePicker').show()" />
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
                <div class='col-md-4'>
                    @Html.ValidationMessageFor(model => model.TimeTo)
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class='col-md-8'>
                <div class="col-md-2"></div>
                <div class="col-md-4">
                    <input type="submit" value="Zobrazit" class="btn btn-default" />
                </div>
                <div class="col-md-4"></div>
            </div>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#datetimepickerFrom').datetimepicker({ language: "cs" });
                $('#datetimepickerTo').datetimepicker({ language: "cs" });
                $("#datetimepickerFrom").on("dp.change", function (e) {
                    $('#datetimepickerTo').data("DateTimePicker").setMinDate(e.date);
                    var date = new Date(e.date.toString());
                    $('#TimeFrom').val(date.getTime() / 1000);
                });
                $("#datetimepickerTo").on("dp.change", function (e) {
                    $('#datetimepickerFrom').data("DateTimePicker").setMaxDate(e.date);
                    var date = new Date(e.date.toString());
                    $('#TimeTo').val(date.getTime() / 1000);
                });
            });
        </script>
    </div>
}
<p>
    @Html.ActionLink("Editovat", "Edit", new { id = Model.DeviceId }) |
    @Html.ActionLink("Zpět na seznam", "Index") |
    @Html.ActionLink("Zobrazit na mapě", "MapActualPosition", "Gps", new { deviceId = Model.DeviceId }, null)
</p>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MobileTracker/Views/Device/Edit.cshtml
@model MobileTracker.Models.Db.Device

@{
    ViewBag.Title = "Editovat";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Device</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.DeviceId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Imei, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Imei)
                @Html.ValidationMessageFor(model => model.Imei)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber)
                @Html.ValidationMessageFor(model => model.PhoneNumber)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupId, "GroupId", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GroupId", String.Empty)
                @Html.ValidationMessageFor(model => model.GroupId)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zpět na seznam", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MobileTracker/Views/Device/Index.cshtml
@model IEnumerable<MobileTracker.Models.Db.Device>

@{
    ViewBag.Title = "Přehled";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Vytvořit", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Group.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Imei)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Group.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Imei)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @Html.ActionLink("Editovat", "Edit", new { id=item.DeviceId }) |
            @Html.ActionLink("Detail", "Details", new { id=item.DeviceId }) |
            @Html.ActionLink("Smazat", "Delete", new { id=item.DeviceId })
        </td>
    </tr>
}

</table>

MobileTracker/Views/Device/IndexUserView.cshtml
@using System.Web.UI.WebControls
@using Microsoft.AspNet.Identity
@using MobileTracker.Models
@using MobileTracker.Models.Manager
@model IEnumerable<MobileTracker.Models.Db.Device>

@{
    ViewBag.Title = "Přehled";
}

<h2>Index</h2>

<p>
    
@*    @Html.ActionLink("Nové zařízení", "CreateGroup", )*@
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Imei)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Imei)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PhoneNumber)
        </td>
        <td>
            @if (User.IsInRole(IdentityManager.RoleGroupAdmin))
            {
                @Html.ActionLink("Editovat", "Edit", new {id = item.DeviceId}) 
            }
            @Html.ActionLink("Detail", "Details", new { id=item.DeviceId })
            @if (User.IsInRole(IdentityManager.RoleGroupAdmin))
            {
                @Html.ActionLink("Smazat", "Delete", new {id = item.DeviceId})
            }
        </td>
    </tr>
}

</table>