MobileTracker/Controllers/DeviceController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using MobileTracker.Models;
using MobileTracker.Models.Db;

namespace MobileTracker.Controllers
{
    public class DeviceController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Device/
        public ActionResult Index()
        {
            var devices = db.Devices.Include(d => d.Group);
            return View(devices.ToList());
        }

        // GET: /Device/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            GpsMapTimeSelect mapTimeSelect = new GpsMapTimeSelect();
            mapTimeSelect.Device = device;
            mapTimeSelect.DeviceId = device.DeviceId;
            return View(mapTimeSelect);
        }

        // GET: /Device/Create
        public ActionResult Create()
        {
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name");
            return View();
        }

        // POST: /Device/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="DeviceId,Name,Imei,PhoneNumber,GroupId")] Device device)
        {
            if (ModelState.IsValid)
            {
                db.Devices.Add(device);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name", device.GroupId);
            return View(device);
        }

        // GET: /Device/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name", device.GroupId);
            return View(device);
        }

        // POST: /Device/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="DeviceId,Name,Imei,PhoneNumber,GroupId")] Device device)
        {
            if (ModelState.IsValid)
            {
                db.Entry(device).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GroupId = new SelectList(db.Groups, "GroupId", "Name", device.GroupId);
            return View(device);
        }

        // GET: /Device/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Device device = db.Devices.Find(id);
            if (device == null)
            {
                return HttpNotFound();
            }
            return View(device);
        }

        // POST: /Device/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Device device = db.Devices.Find(id);
            db.Devices.Remove(device);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        [Authorize]
        public ActionResult IndexUserView()
        {
            var user = db.Users.Find(User.Identity.GetUserId());
            var group = user.Group;
            var devices = group.Devices;
            return View(devices.ToList());
        }

        public JsonResult IsImeiAvailable(string imei, int deviceId)
        {
            return Json(!db.Devices.Any(i => i.Imei == imei && i.DeviceId != deviceId), JsonRequestBehavior.AllowGet);
        }
    }
}

MobileTracker/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MobileTracker.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "";

            return View();
        }
    }
}

MobileTracker/Views/Home/About.cshtml
@{
    ViewBag.Title = "O projektu";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Projekt je vytvořen jako školní diplomová práce. Za nic v této práci neručím. Použití na vlastní nebezpečí.</p>

MobileTracker/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Kontakt";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    Mobile Tracker<br />
    Školní projekt<br />
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:springer@example.com">Support@example.com</a><br />
</address>

MobileTracker/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Úvodní stránka";
}

<div class="jumbotron">
    <h1>Mobile Tracker</h1>
    <p class="lead">Vítejte na stráka pro trackerování Vašeho mobilního zařízení.</p>
    @if (Request.IsAuthenticated)
    {
        <p>@Html.ActionLink("Seznam zařízení", "IndexUserView", "Device", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "btn btn-primary btn-large" })</p>
    }
    else
    {
        <p>@Html.ActionLink("Přihlásit", "Login", "Account", routeValues: null, htmlAttributes: new {id = "loginLink", @class = "btn btn-primary btn-large"})</p>

    }    
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Novinky v aplikaci</h2>
        <p>Už funguje přihlášení</p>
        <p>Trackerování Windows Phone 8</p>
        <p>Zobrazení poslední polohy na mapě</p>
    </div>
    <div class="col-md-4">
        <p>&nbsp;</p>
    </div>
    <div class="col-md-4">
        <h2>Plánované novinky</h2>
        <p>Zobrazení bodů dle časového výběru na mapě</p>
        <p>Trackerování iPhone</p>
    </div>
</div>