MobileTracker/Models/Group.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using MobileTracker.Controllers;

namespace MobileTracker.Models
{
    public class Group
    {
        [Key]
        [Required]
        public int GroupId { get; set; }

        [Required]
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<ApplicationUser> ApplicationUsers { get; set; }
        public virtual ICollection<Device> Devices { get; set; } 
    }
}

MobileTracker/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MobileTracker.Models;
using PagedList;


namespace MobileTracker.Controllers
{
    public class GroupController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: /Group/
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;
            var groups = from s in db.Groups select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                groups = groups.Where(i => i.Name.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    groups = groups.OrderByDescending(s => s.Name);
                    break;
                default:
                    groups = groups.OrderBy(s => s.Name);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(groups.ToPagedList(pageNumber, pageSize));
        }

        // GET: /Group/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group groupdb = db.Groups.Find(id);
            if (groupdb == null)
            {
                return HttpNotFound();
            }
            return View(groupdb);
        }

        // GET: /Group/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Group/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="GroupId,Name,Description")] Group groupdb)
        {
            if (ModelState.IsValid)
            {
                db.Groups.Add(groupdb);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(groupdb);
        }

        // GET: /Group/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group groupdb = db.Groups.Find(id);
            if (groupdb == null)
            {
                return HttpNotFound();
            }
            return View(groupdb);
        }

        // POST: /Group/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="GroupId,Name,Description")] Group groupdb)
        {
            if (ModelState.IsValid)
            {
                db.Entry(groupdb).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(groupdb);
        }

        // GET: /Group/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group groupdb = db.Groups.Find(id);
            if (groupdb == null)
            {
                return HttpNotFound();
            }
            return View(groupdb);
        }

        // POST: /Group/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Group groupdb = db.Groups.Find(id);
            db.Groups.Remove(groupdb);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MobileTracker/Views/Group/Create.cshtml
@model MobileTracker.Models.Group

@{
    ViewBag.Title = "Vytvořit";
}

<h2>Vytvořit</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Group</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MobileTracker/Views/Group/Delete.cshtml
@model MobileTracker.Models.Group

@{
    ViewBag.Title = "Smazat";
}

<h2>Smazat</h2>

<h3>Opravdu odstranit?</h3>
<div>
    <h4>Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Zpět na seznam", "Index")
        </div>
    }
</div>

MobileTracker/Views/Group/Details.cshtml
@using MobileTracker.Models
@model MobileTracker.Models.Group

@{
    ViewBag.Title = "Detail";
}

<h2>Detail</h2>

<div>
    <h4>Group</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Vytvořit", "CreateUserGroup", "Account", Model, null)
</p>
<table class="table">
    <tr>
        <th>
            Uzivatelske jmeno
        </th>
        <th>
            Jmeno
        </th>
        <th>
            Prijmeni
        </th>
        <th>
            E-mail
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.ApplicationUsers) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Editovat", "Edit", "Account", new { id = item.UserName }, null) |
                @Html.ActionLink("Detail", "UserRoles", "Account", new { id = item.UserName }, null) |
                @Html.ActionLink("Smazat", "Delete", "Account", new { id = item.UserName }, null)
            </td>
        </tr>
    }

</table>
<p>
    @Html.ActionLink("Editovat", "Edit", new { id = Model.GroupId }) |
    @Html.ActionLink("Zpět na seznam", "Index")
</p>

MobileTracker/Views/Group/Edit.cshtml
@model MobileTracker.Models.Group

@{
    ViewBag.Title = "Editovat";
}

<h2>Editovat</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Skupina</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.GroupId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Zpět na seznam", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MobileTracker/Views/Group/Index.cshtml
@*@model IEnumerable<MobileTracker.Models.Group>*@
@model PagedList.IPagedList<MobileTracker.Models.Group>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Skupiny";
}

<h2>Skupiny</h2>

<p>
    @Html.ActionLink("Vytvořit skupinu", "Create")
</p>
@using (Html.BeginForm("Index", "Group", FormMethod.Get))
{
    <p>
        Najít skupinu: @Html.TextBox("searchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Vyhledat" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Jméno skupiny", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Popis
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.ActionLink("Editovat", "Edit", new { id=item.GroupId }) |
            @Html.ActionLink("Detail", "Details", new { id=item.GroupId }) |
            @Html.ActionLink("Smazat", "Delete", new { id=item.GroupId })
        </td>
    </tr>
}

</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))